# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 09:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0002_remove_userprofile_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_no', models.CharField(max_length=128)),
                ('app_sub_time', models.DateTimeField(verbose_name='submission time')),
                ('vehicle_type', models.CharField(choices=[('Ambassador Car', ''), ('Tata Seira', 'Tata Seira'), ('Tata Sumo', 'Tata Sumo'), ('Toyota Qualis', 'Toyota Qualis'), ('Toyota Innova', 'Toyota Innova'), ('Maruti Ciaz', 'Maruti Ciaz'), ('Mini Bus', 'Mini Bus'), ('S.M.Bus', 'S.M.Bus'), ('Stallion', 'Stallion')], default='Ambassador Car', max_length=30)),
                ('date_jour', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('purpose', models.CharField(max_length=128)),
                ('source', models.CharField(max_length=128)),
                ('others', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sanctioned', 'Sanctioned'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
