# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_userinbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinbox',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserInbox',
        ),
    ]
