# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_userinbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinbox',
            name='destination',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
