# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_userinbox_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinbox',
            name='app_sub_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
