# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_auto_20170623_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
