# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_auto_20170623_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.UserProfile'),
        ),
    ]
