# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-01 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_auto_20170624_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_t', models.TimeField(blank=True)),
                ('to_t', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_name', models.CharField(max_length=128)),
                ('capacity', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinbox',
            name='vehicle_type',
        ),
    ]
