# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-01 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_auto_20170701_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, upload_to='veh_pics'),
        ),
    ]
