# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0017_slot_veh'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
