# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0018_userprofile_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_no', models.CharField(max_length=128)),
                ('Suggestions', models.TextField()),
                ('Remarks', models.CharField(max_length=128)),
                ('fb_sub_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.UserProfile')),
            ],
        ),
    ]
