# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0019_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinbox',
            old_name='date_jour',
            new_name='date_of_journey',
        ),
    ]
