# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0020_auto_20170703_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Suggestions',
            field=models.CharField(max_length=128),
        ),
    ]
