# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0021_auto_20170704_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=128)),
                ('reply_sub_time', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.FeedBack')),
            ],
        ),
    ]
