# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0022_feedbackreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackreply',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
